config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
	  get '/login' => 'login#new'
	  post '/login' => 'login#create'
	  get '/logout' => 'login#destroy'

    get '/profile' => 'profile#edit'
    patch '/profile' => 'profile#update'

    get '/config' => 'config#edit'
    patch '/config' => 'config#update'

	  resources :users
	  resources :exercises
  	resources :teams
    resources :categories

	  root 'index#index'
	end

  get '/login' => 'login#new'
  post '/login' => 'login#create'
  get '/logout' => 'login#destroy'

  get '/register' => 'register#new'
  post '/register' => 'register#create'

  get '/profile' => 'profile#edit'
  patch '/profile' => 'profile#update'

  patch '/upload' => 'upload#upload'

	root 'index#index'
end

app/views/index/_active.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% @exercises.each do |exercise| %>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="heading<%= exercise.id %>">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion"
            href="#collapse<%= exercise.id %>" aria-expanded="true"
            aria-controls="collapse<%= exercise.id %>">
            <%= exercise.title %>
          </a>
        </h4>
      </div>
      <div id="collapse<%= exercise.id %>" class="panel-collapse collapse"
        role="tabpanel" aria-labelledby="heading<%= exercise.id %>">
        <div class="panel-body">
          <%= simple_format exercise.text %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% if current_team.files.present? %>
  <div class="alert alert-info">
    <b><%= I18n.t('messages.already_sent_exercises') %></b>
    <br>
    <%= I18n.t('messages.sent_on') %> <%= l current_team.files_updated_at, format: :short %>
  </div>
<% else %>
  <%= form_for current_team, :url => upload_path, html: { multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :files %>
      <%= f.file_field :files, class: "form-control", :accept => "application/zip,application/octet-stream", :required => true %>
    </div>

    <%= f.submit I18n.t('actions.send'), class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/index/index.html.erb
<%= render 'application/messages' %>

<% if current_config.active? %>
  <%= render 'active' %>
<% else %>
  <div class="alert alert-info">
    <%= I18n.t('messages.exercises_will_be_available_on') %> <b><%= l current_config.start_time, format: :short %></b>
  </div>
<% end %>