config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
	  get '/login' => 'login#new'
	  post '/login' => 'login#create'
	  get '/logout' => 'login#destroy'

    get '/profile' => 'profile#edit'
    patch '/profile' => 'profile#update'

    get '/config' => 'config#edit'
    patch '/config' => 'config#update'

	  resources :users
	  resources :exercises
  	resources :teams
    resources :categories

	  root 'index#index'
	end

  get '/login' => 'login#new'
  post '/login' => 'login#create'
  get '/logout' => 'login#destroy'

  get '/register' => 'register#new'
  post '/register' => 'register#create'

  get '/profile' => 'profile#edit'
  patch '/profile' => 'profile#update'

  patch '/upload' => 'upload#upload'

	root 'index#index'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to [:admin, @category], notice: I18n.t('messages.create_success', :model => Category.model_name.human)
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to [:admin, @category], notice: I18n.t('messages.update_success', :model => Category.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_url, notice: I18n.t('messages.destroy_success', :model => Category.model_name.human)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, category] do |f| %>
  <%= render 'application/messages', errors: category.errors %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", :required => true %>
  </div>

  <%= f.submit I18n.t('actions.save'), class: "btn btn-success" %>
<% end %>

app/views/admin/categories/_page_header.html.erb
<header id="page-header">
  <div class="title">
    <h1><%= Category.model_name.human(count: 2) %></h1>
  </div>
  <div class="actions">
    <%= link_to I18n.t('actions.new'), new_admin_category_path, class: 'btn btn-default' %>
    <%= link_to I18n.t('actions.list'), admin_categories_path, class: 'btn btn-default' %>
  </div>
</header>

app/views/admin/categories/edit.html.erb
<%= render 'page_header' %>
<%= render 'form', category: @category %>

app/views/admin/categories/index.html.erb
<%= render 'page_header' %>
<%= render 'application/messages' %>

<table class="table">
  <thead>
    <tr>
      <th><%= I18n.t('helpers.label.category.name') %></th>
      <th class="actions"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to I18n.t('actions.show'), [:admin, category], class: 'btn btn-small btn-default' %>
          <%= link_to I18n.t('actions.edit'), edit_admin_category_path(category), class: 'btn btn-small btn-default' %>
          <%= link_to I18n.t('actions.destroy'), [:admin, category], method: :delete, class: 'btn btn-small btn-danger', data: { confirm: I18n.t('messages.are_you_sure') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<%= render 'page_header' %>
<%= render 'form', category: @category %>

app/views/admin/categories/show.html.erb
<%= render 'page_header' %>
<%= render 'application/messages' %>

<%= form_for [:admin, @category] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <p class="form-control-static"><%= @category.name %></p>
  </div>
<% end %>