config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
	  get '/login' => 'login#new'
	  post '/login' => 'login#create'
	  get '/logout' => 'login#destroy'

    get '/profile' => 'profile#edit'
    patch '/profile' => 'profile#update'

    get '/config' => 'config#edit'
    patch '/config' => 'config#update'

	  resources :users
	  resources :exercises
  	resources :teams
    resources :categories

	  root 'index#index'
	end

  get '/login' => 'login#new'
  post '/login' => 'login#create'
  get '/logout' => 'login#destroy'

  get '/register' => 'register#new'
  post '/register' => 'register#create'

  get '/profile' => 'profile#edit'
  patch '/profile' => 'profile#update'

  patch '/upload' => 'upload#upload'

	root 'index#index'
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :name, presence: true
  validates :email, presence: true, uniqueness: true

	scope :all_except, ->(user) { where.not(id: user) }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all_except current_user
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to [:admin, @user], notice: I18n.t('messages.create_success', :model => User.model_name.human)
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: I18n.t('messages.update_success', :model => User.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: I18n.t('messages.destroy_success', :model => User.model_name.human)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationAdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: I18n.t('messages.create_success', :model => User.model_name.human) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: I18n.t('messages.update_success', :model => User.model_name.human) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: I18n.t('messages.destroy_success', :model => User.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, user] do |f| %>
  <%= render 'application/messages', errors: user.errors %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control", :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <%= f.submit I18n.t('actions.save'), class: "btn btn-success" %>
<% end %>

app/views/admin/users/_page_header.html.erb
<header id="page-header">
  <div class="title">
    <h1><%= User.model_name.human(count: 2) %></h1>
  </div>
  <div class="actions">
    <%= link_to I18n.t('actions.new'), new_admin_user_path, class: 'btn btn-default' %>
    <%= link_to I18n.t('actions.list'), admin_users_path, class: 'btn btn-default' %>
  </div>
</header>

app/views/admin/users/edit.html.erb
<%= render 'page_header' %>
<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<%= render 'page_header' %>
<%= render 'application/messages' %>

<table class="table">
  <thead>
    <tr>
      <th><%= I18n.t('helpers.label.user.name') %></th>
      <th><%= I18n.t('helpers.label.user.email') %></th>
      <th class="actions"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to I18n.t('actions.show'), [:admin, user], class: 'btn btn-small btn-default' %>
          <%= link_to I18n.t('actions.edit'), edit_admin_user_path(user), class: 'btn btn-small btn-default' %>
          <%= link_to I18n.t('actions.destroy'), [:admin, user], method: :delete, class: 'btn btn-small btn-danger', data: { confirm: I18n.t('messages.are_you_sure') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%= render 'page_header' %>
<%= render 'form', user: @user %>

app/views/admin/users/show.html.erb
<%= render 'page_header' %>
<%= render 'application/messages' %>

<%= form_for [:admin, @user] do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<p class="form-control-static"><%= @user.name %></p>
	</div>

	<div class="form-group">
		<%= f.label :email %>
		<p class="form-control-static"><%= @user.email %></p>
	</div>
<% end %>