config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
	  get '/login' => 'login#new'
	  post '/login' => 'login#create'
	  get '/logout' => 'login#destroy'

    get '/profile' => 'profile#edit'
    patch '/profile' => 'profile#update'

    get '/config' => 'config#edit'
    patch '/config' => 'config#update'

	  resources :users
	  resources :exercises
  	resources :teams
    resources :categories

	  root 'index#index'
	end

  get '/login' => 'login#new'
  post '/login' => 'login#create'
  get '/logout' => 'login#destroy'

  get '/register' => 'register#new'
  post '/register' => 'register#create'

  get '/profile' => 'profile#edit'
  patch '/profile' => 'profile#update'

  patch '/upload' => 'upload#upload'

	root 'index#index'
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  layout 'login'

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(register_params)

    if @team.save
      session[:team_id] = @team.id
      redirect_to root_url, notice: I18n.t('messages.welcome', :name => @team.name)
    else
      render :new
    end
  end

  private
    def register_params
      params.require(:team).permit(:name, :login, :password, :password_confirmation, :members, :category_id)
    end
end

app/views/register/_form.html.erb
<div class="panel register-width">
  <%= form_for team, :url => register_path do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", :required => true  %>
    </div>

    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {:prompt=>false}, {:class=>'form-control'} %>
    </div>

    <div class="form-group">
      <%= f.label :login %>
      <%= f.text_field :login, class: "form-control", :required => true %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :members %>
      <%= f.text_area :members, class: "form-control", rows: 8 %>
    </div>

    <%= render 'application/messages', errors: team.errors %>

    <%= f.submit I18n.t('actions.send'), class: "btn btn-block btn-success" %>
  <% end %>
</div>

app/views/register/new.html.erb
<div class="logo-header">
  <svg xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 0 1463 1304" style="image-rendering:optimizeQuality;shape-rendering:geometricPrecision;text-rendering:geometricPrecision"><path class="fil0" d="M284 788c391 0 888 313 969 468 6 13 9 22 9 32l17-16c48-58 51-62 77-100 32-58 42-74 71-149l3-9c-9-172-581-462-1004-462-158 0-274 42-348 116-58 58-81 136-78 226 7 91 42 184 107 268-62-94-84-187-58-255 19-55 71-116 213-119 6 0 16 0 22 0l0 0z"/><path class="fil0" d="M688 36c90 0 181 12 265 41 167 59 309 162 403 294-77-158-219-281-387-335-71-23-142-36-213-36-107 0-207 26-301 71 75-23 152-35 233-35l0 0z"/><path class="fil0" d="M688 1304l265 0-133-226-22 39-7-3c-174-68-342-100-474-91-7 0-13 0-20 0-97 10-161 45-177 100-10 46 6 100 51 155-9-26-9-48 0-68 17-29 55-45 110-48 94-6 223 23 358 78 20 6 39 16 59 25l6 4-16 35 0 0z"/><path class="fil0" d="M384 297c427 0 975 307 1079 497l0-6c0-46-4-49-13-123-4-10-7-26-10-39l-3-13c-13-38-42-71-62-90-219-203-571-342-874-342-97 0-184 16-262 45l-6 0-36-68-119 197 229 10-32-62 13 0c29-6 64-6 96-6l0 0z"/></svg>
</div>

<div class="login-header">
  <h1><%= I18n.t('actions.signup_oesticoding') %></h1>
</div>

<%= render 'form', team: @team %>

<p class="create-an-account register-width">
  <%= I18n.t('messages.already_registered') %>
  <a href="<%= login_path %>">Login</a>.
</p>

<div class="login-footer">
  <ul >
    <li><a href="https://github.com/OESTIDigital/oesti-coding-sign-up/blob/master/README.md" target="_blank">Regras</a></li>
    <li><a href="http://oestidigital.com.br/" target="_blank">Site</a></li>
    <li><a href="https://github.com/OESTIDigital" target="_blank">GitHub</a></li>
  </ul>
</div>